title: The future of Tesla
author: Mike Sheppard
email: Mike.sheppard145@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog, we are going to be talking about the impacts that Tesla will have on the future of solar energy, electric cars and much more.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
